-- ============================================================
-- TinyClaw 核心持久化 Schema（兼容 PostgreSQL 与 H2）
-- ============================================================

-- 会话表：Agent 的顶层上下文
CREATE TABLE agent_sessions (
    id              VARCHAR(36) PRIMARY KEY,
    workspace_path  VARCHAR(512) NOT NULL,
    status          VARCHAR(32)  NOT NULL DEFAULT 'active',
    metadata        TEXT,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 运行表：一次 Agent 任务的完整生命周期
CREATE TABLE agent_runs (
    id              VARCHAR(36) PRIMARY KEY,
    session_id      VARCHAR(36)  NOT NULL,
    status          VARCHAR(32)  NOT NULL DEFAULT 'running',
    max_turns       INT          NOT NULL DEFAULT 20,
    current_turn    INT          NOT NULL DEFAULT 0,
    error_reason    TEXT,
    started_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at        TIMESTAMP,
    CONSTRAINT fk_runs_session FOREIGN KEY (session_id) REFERENCES agent_sessions(id)
);

-- 消息表：对话历史（system / user / assistant / tool）
CREATE TABLE agent_messages (
    id              VARCHAR(36) PRIMARY KEY,
    session_id      VARCHAR(36)  NOT NULL,
    run_id          VARCHAR(36),
    role            VARCHAR(32)  NOT NULL,
    content         TEXT,
    tool_calls      TEXT,
    tool_call_id    VARCHAR(64),
    sequence_number INT          NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_messages_session FOREIGN KEY (session_id) REFERENCES agent_sessions(id),
    CONSTRAINT fk_messages_run FOREIGN KEY (run_id) REFERENCES agent_runs(id)
);

-- 工具执行表：每次 ToolCall 的输入输出
CREATE TABLE tool_executions (
    id                VARCHAR(36) PRIMARY KEY,
    run_id            VARCHAR(36)  NOT NULL,
    session_id        VARCHAR(36)  NOT NULL,
    tool_name         VARCHAR(128) NOT NULL,
    tool_call_id      VARCHAR(64)  NOT NULL,
    arguments         TEXT,
    result            TEXT,
    is_error          BOOLEAN      NOT NULL DEFAULT FALSE,
    execution_time_ms INT,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tool_execs_run FOREIGN KEY (run_id) REFERENCES agent_runs(id),
    CONSTRAINT fk_tool_execs_session FOREIGN KEY (session_id) REFERENCES agent_sessions(id)
);

-- 审批请求表：高危操作的人工审批
CREATE TABLE approval_requests (
    id              VARCHAR(36) PRIMARY KEY,
    run_id          VARCHAR(36)  NOT NULL,
    session_id      VARCHAR(36)  NOT NULL,
    tool_name       VARCHAR(128) NOT NULL,
    tool_call_id    VARCHAR(64)  NOT NULL,
    command_or_path VARCHAR(512),
    status          VARCHAR(32)  NOT NULL DEFAULT 'PENDING',
    requested_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at     TIMESTAMP,
    resolved_by     VARCHAR(128),
    rejection_reason TEXT,
    CONSTRAINT fk_approvals_run FOREIGN KEY (run_id) REFERENCES agent_runs(id),
    CONSTRAINT fk_approvals_session FOREIGN KEY (session_id) REFERENCES agent_sessions(id)
);

-- 链路追踪表：可观测性 Span 数据
CREATE TABLE trace_spans (
    id             VARCHAR(36) PRIMARY KEY,
    run_id         VARCHAR(36)  NOT NULL,
    session_id     VARCHAR(36)  NOT NULL,
    parent_span_id VARCHAR(36),
    span_name      VARCHAR(256) NOT NULL,
    started_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at       TIMESTAMP,
    attributes     TEXT,
    CONSTRAINT fk_spans_run FOREIGN KEY (run_id) REFERENCES agent_runs(id),
    CONSTRAINT fk_spans_session FOREIGN KEY (session_id) REFERENCES agent_sessions(id)
);

-- 用量记录表：Token 与成本统计
CREATE TABLE usage_records (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id               VARCHAR(36),
    session_id           VARCHAR(36),
    provider             VARCHAR(64),
    model                VARCHAR(128),
    prompt_tokens        INT          NOT NULL DEFAULT 0,
    completion_tokens    INT          NOT NULL DEFAULT 0,
    total_tokens         INT          NOT NULL DEFAULT 0,
    estimated_cost_cny   DECIMAL(12, 6),
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_usage_run FOREIGN KEY (run_id) REFERENCES agent_runs(id),
    CONSTRAINT fk_usage_session FOREIGN KEY (session_id) REFERENCES agent_sessions(id)
);

-- ============================================================
-- 常用查询索引
-- ============================================================
CREATE INDEX idx_messages_session_seq   ON agent_messages(session_id, sequence_number);
CREATE INDEX idx_runs_session_status    ON agent_runs(session_id, status);
CREATE INDEX idx_tool_execs_run         ON tool_executions(run_id);
CREATE INDEX idx_approvals_run_status   ON approval_requests(run_id, status);
CREATE INDEX idx_spans_run              ON trace_spans(run_id);
CREATE INDEX idx_usage_run              ON usage_records(run_id);
